/* Generated by scripts/build.mjs from data/*.csv. Do not edit by hand. */
window.WHEEL_DATA = {
 "systems": [
  {
   "key": "cardiac",
   "name": "Cardiac",
   "colour": "#C8402F",
   "order": 0
  },
  {
   "key": "respiratory",
   "name": "Respiratory",
   "colour": "#2E7CC4",
   "order": 1
  },
  {
   "key": "renal",
   "name": "Renal and metabolic",
   "colour": "#1E8F6E",
   "order": 2
  },
  {
   "key": "gastro",
   "name": "Gastro and liver",
   "colour": "#A8497E",
   "order": 3
  },
  {
   "key": "neurology",
   "name": "Neurology",
   "colour": "#7A4FBF",
   "order": 4
  },
  {
   "key": "infection",
   "name": "Infection",
   "colour": "#D18A16",
   "order": 5
  },
  {
   "key": "drugs",
   "name": "Drugs and prescribing",
   "colour": "#55606E",
   "order": 6
  }
 ],
 "topics": [
  {
   "id": 1,
   "system": "cardiac",
   "theme": "Cardiac rhythm",
   "title": "Aspirin is not an anticoagulant option in AF",
   "principle": "AF stroke is a stasis driven fibrin thrombus forming in the left atrial appendage. It is not a platelet driven arterial plaque event, so an antiplatelet is the wrong drug class for the wrong clot.",
   "rule": "Score thromboembolic risk with CHA2DS2-VASc, assess bleeding risk with ORBIT, and offer a DOAC first line. Bleeding risk is used to find and modify reversible risk factors, not to withhold anticoagulation.",
   "trap": "Withholding anticoagulation solely because of age or falls risk. Use bleeding assessment to address modifiable risks and review treatment, not as an automatic reason to deny stroke prevention.",
   "takehome": "NICE explicitly says do not offer aspirin monotherapy for stroke prevention in AF.",
   "source": "NICE NG196",
   "check": {
    "label": "NICE NG196 recommendations",
    "url": "https://www.nice.org.uk/guidance/ng196/chapter/recommendations"
   }
  },
  {
   "id": 2,
   "system": "cardiac",
   "theme": "Cardiac rhythm",
   "title": "Why atropine fails in complete heart block",
   "principle": "Atropine blocks parasympathetic activity at the sinoatrial and AV nodes. It is unlikely to help when high-grade block is below the AV node, particularly when the QRS is broad.",
   "rule": "For adverse features, give atropine 500 micrograms IV and repeat every 3 to 5 minutes to a maximum of 3 mg, except in high-degree AV block with a wide QRS, where RCUK advises against it because it may be ineffective and can worsen the block. Prepare transcutaneous pacing and seek expert help; alternatives include isoprenaline or adrenaline infusion.",
   "trap": "Cycling through atropine in a broad-QRS high-grade block while definitive pacing is delayed. In a transplanted heart atropine can cause high-grade block or sinus arrest; use aminophylline for severe bradycardia.",
   "takehome": "Broad-QRS high-grade block means prepare pacing and expert support, not repeated atropine.",
   "source": "Resuscitation Council UK ALS 2025",
   "check": {
    "label": "RCUK adult ALS guideline 2025",
    "url": "https://www.resus.org.uk/professional-library/2025-resuscitation-guidelines/adult-advanced-life-support-guidelines"
   }
  },
  {
   "id": 3,
   "system": "cardiac",
   "theme": "Cardiac rhythm",
   "title": "Adenosine is 6, 12, 18—and delivery matters",
   "principle": "Adenosine has a half life under 10 seconds because it is taken up by red cells and endothelium almost immediately. It only works if a bolus reaches the AV node intact.",
   "rule": "Give 6 mg, then 12 mg, then 18 mg as rapid IV boluses, each followed immediately by a rapid saline flush through a well-functioning line that is as proximal as practical. Record a rhythm strip throughout, because AV block may reveal the underlying rhythm even if the tachycardia does not terminate.",
   "trap": "Injecting slowly or through poorly functioning access, then treating failed delivery as diagnostic failure. Adenosine should be used cautiously when the diagnosis is uncertain and avoided in irregular broad-complex tachycardia.",
   "takehome": "Use a rapid bolus and immediate flush, and record the rhythm strip.",
   "source": "Resuscitation Council UK adult tachyarrhythmia algorithm, March 2026",
   "check": {
    "label": "RCUK adult tachyarrhythmia algorithm",
    "url": "https://www.resus.org.uk/sites/default/files/2026-03/Adult%20tachyarrhythmia%20algorithm%20V3%20March%202026.pdf"
   }
  },
  {
   "id": 4,
   "system": "cardiac",
   "theme": "Chest pain and ACS",
   "title": "The troponin pathway matters more than one elevated value",
   "principle": "Troponin above the 99th centile shows myocardial injury. A rise or fall supports acute injury, while myocardial infarction also requires clinical evidence of ischaemia; renal disease, heart failure and other illnesses can elevate troponin without infarction.",
   "rule": "Follow an assay-specific, validated local pathway and account for time from symptom onset. Some pathways allow rule-out with one very low high-sensitivity troponin in selected low-risk patients; otherwise repeat at the pathway's specified interval.",
   "trap": "Calling every mildly elevated troponin an NSTEMI, or using an early value below the 99th centile to rule out ACS when the validated pathway does not allow it.",
   "takehome": "Use the validated pathway and clinical story; do not diagnose MI from one elevated value.",
   "source": "NICE HTG552 (formerly DG40) and validated local hs-troponin pathways",
   "check": {
    "label": "NICE high-sensitivity troponin recommendations",
    "url": "https://www.nice.org.uk/guidance/HTG552/chapter/1-Recommendations"
   }
  },
  {
   "id": 5,
   "system": "cardiac",
   "theme": "Chest pain and ACS",
   "title": "High-risk ACS patterns can lack classic ST elevation",
   "principle": "Standard ST-elevation criteria do not capture every coronary occlusion or every patient at high risk of imminent infarction.",
   "rule": "Posterior infarction may show horizontal ST depression and tall R waves in V1 to V3; obtain V7 to V9. A de Winter pattern is associated with proximal LAD occlusion. Deeply inverted or biphasic T waves in V2 to V3 while pain-free suggest Wellens syndrome and critical proximal LAD disease.",
   "trap": "Stress testing a Wellens patient. They need angiography, not a treadmill.",
   "takehome": "ST depression in V1 to V3 should trigger posterior leads before anything else.",
   "source": "ESC acute coronary syndromes guideline 2023",
   "check": {
    "label": "ESC acute coronary syndromes guideline",
    "url": "https://www.escardio.org/guidelines/clinical-practice-guidelines/all-esc-practice-guidelines/acute-coronary-syndromes/"
   }
  },
  {
   "id": 6,
   "system": "cardiac",
   "theme": "Chest pain and ACS",
   "title": "The dissection that presents as an inferior STEMI",
   "principle": "A type A dissection flap can extend into a coronary ostium, most commonly the right, producing genuine inferior infarction. The ECG is real. The diagnosis is still dissection.",
   "rule": "Before thrombolysis for an inferior STEMI, rapidly consider acute aortic syndrome: abrupt severe pain, pulse or blood-pressure differential, new aortic regurgitation, neurological deficit or other high-risk features. A widened mediastinum is supportive but neither sensitive nor specific, and absence of classic features does not exclude dissection.",
   "trap": "Full anticoagulation and antiplatelet loading in an undiagnosed dissection.",
   "takehome": "Inferior STEMI with hypotension needs right sided leads and a moment's thought about the aorta.",
   "source": "ESC peripheral arterial and aortic diseases guideline 2024",
   "check": {
    "label": "ESC aortic diseases guideline",
    "url": "https://www.escardio.org/guidelines/clinical-practice-guidelines/all-esc-practice-guidelines/peripheral-arterial-and-aortic-diseases/"
   }
  },
  {
   "id": 7,
   "system": "neurology",
   "theme": "Syncope and dizziness",
   "title": "Dizziness is about timing and triggers, not quality",
   "principle": "Asking whether it is spinning or lightheaded is unreliable, because patients describe the same symptom differently on different days. Timing and triggers are reproducible. Quality is not.",
   "rule": "Sort by syndrome: continuous acute vestibular syndrome, triggered episodic symptoms such as BPPV, or spontaneous episodic symptoms. Use Dix-Hallpike for suspected posterior-canal BPPV. HINTS is for a trained examiner assessing acute vestibular syndrome with nystagmus.",
   "trap": "Applying HINTS to a patient who is asymptomatic, has no spontaneous nystagmus, or when the examiner is not trained in the technique.",
   "takehome": "No nystagmus right now means no HINTS.",
   "source": "GRACE-3 acute dizziness guideline and NICE NG127",
   "check": {
    "label": "GRACE-3 acute dizziness guideline",
    "url": "https://www.saem.org/publications/grace/grace-3"
   }
  },
  {
   "id": 8,
   "system": "neurology",
   "theme": "Syncope and dizziness",
   "title": "In HINTS, the normal result is the frightening one",
   "principle": "The head impulse test assesses the vestibulo-ocular reflex. Vestibular neuritis damages that reflex, so the eyes lag and make a corrective saccade. A brainstem stroke leaves the peripheral apparatus intact, so the reflex looks normal.",
   "rule": "In the correct population, central features are a normal head impulse, direction-changing gaze-evoked nystagmus or vertical skew. Any central feature requires urgent stroke assessment; use HINTS only if trained and competent.",
   "trap": "Reassurance from an early CT head, which is insensitive for acute posterior-fossa infarction. In the original high-risk acute vestibular syndrome study, expert HINTS was more sensitive than early MRI—not a result that can be generalised to every dizzy patient or untrained examiner.",
   "takehome": "A normal head impulse in acute continuous vertigo is a red flag, not reassurance.",
   "source": "Kattah et al 2009 and NICE NG127",
   "check": {
    "label": "Kattah et al, HINTS study",
    "url": "https://pubmed.ncbi.nlm.nih.gov/19762709/"
   }
  },
  {
   "id": 9,
   "system": "cardiac",
   "theme": "Syncope and dizziness",
   "title": "Syncope: the six red flags that change the pathway",
   "principle": "Most syncope is benign reflex syncope. The whole job of the assessment is separating that from arrhythmic or structural cardiac syncope, which carries real short term mortality.",
   "rule": "NICE red flags are an abnormal ECG, heart failure or its signs, loss of consciousness during exertion, family history of sudden cardiac death under 40 or inherited cardiac disease, new or unexplained breathlessness, and a heart murmur. Record a 12-lead ECG in the initial assessment.",
   "trap": "Labelling it collapse query cause and moving on. That phrase carries no diagnostic information and tends to close down thinking.",
   "takehome": "Syncope on exertion is cardiac until proven otherwise.",
   "source": "NICE CG109",
   "check": {
    "label": "NICE CG109 recommendations",
    "url": "https://www.nice.org.uk/guidance/cg109/chapter/Recommendations"
   }
  },
  {
   "id": 10,
   "system": "renal",
   "theme": "Electrolytes, part one",
   "title": "Calcium does not lower potassium",
   "principle": "There are three separate jobs in hyperkalaemia and they get confused. Stabilise the myocardium, shift potassium into cells, then remove it from the body. Calcium does only the first.",
   "rule": "For severe hyperkalaemia with ECG changes, give 10 mL of 10% calcium chloride IV over 5 minutes; if calcium chloride is unavailable, give 30 mL of 10% calcium gluconate over 10 minutes. Shift potassium with insulin-glucose and nebulised salbutamol. Removal may require a potassium binder or dialysis, alongside treating the cause.",
   "trap": "Giving calcium and assuming the problem is treated. The serum potassium is entirely unchanged.",
   "takehome": "Calcium buys you time, it does not fix anything.",
   "source": "UK Kidney Association hyperkalaemia guideline",
   "check": {
    "label": "UKKA hyperkalaemia guideline",
    "url": "https://guidelines.ukkidney.org/hyperkalaemia/"
   }
  },
  {
   "id": 11,
   "system": "renal",
   "theme": "Electrolytes, part one",
   "title": "The insulin-glucose hypoglycaemia that happens six hours later",
   "principle": "The insulin used to shift potassium has a longer duration of glycaemic effect than the glucose given with it, particularly in renal impairment where insulin clearance is reduced.",
   "rule": "After insulin-glucose, check capillary glucose at 30, 60, 90 and 120 minutes, then hourly to 6 hours. If pre-treatment glucose is below 7 mmol/L, UKKA advises 10% glucose at 50 mL/hour for 5 hours after the initial treatment.",
   "trap": "Giving the insulin and walking away because the potassium is now normal. This is a recognised cause of avoidable overnight harm and a recurring incident report theme.",
   "takehome": "Pre-treatment glucose under 7 means the patient needs watching for six hours.",
   "source": "UK Kidney Association hyperkalaemia guideline",
   "check": {
    "label": "UKKA hyperkalaemia guideline",
    "url": "https://guidelines.ukkidney.org/hyperkalaemia/"
   }
  },
  {
   "id": 12,
   "system": "renal",
   "theme": "Electrolytes, part one",
   "title": "Low magnesium can make hypokalaemia refractory",
   "principle": "Magnesium normally inhibits the ROMK channel in the distal nephron. When magnesium is depleted that inhibition is lifted, the kidney wastes potassium continuously, and replacement flows straight into the urine.",
   "rule": "In any refractory hypokalaemia, check and replace magnesium. It is common in diuretic use, alcohol dependence, diarrhoea, refeeding, and after prolonged PPI therapy.",
   "trap": "Prescribing a fourth bag of potassium and rechecking the level, with no magnesium ever measured.",
   "takehome": "Hypokalaemia that will not budge means check the magnesium.",
   "source": "Renal physiology and clinical reviews of refractory hypokalaemia",
   "check": {
    "label": "Review of distal potassium handling",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC3074996/"
   }
  },
  {
   "id": 13,
   "system": "renal",
   "theme": "Electrolytes and diabetes",
   "title": "Hyponatraemia: treat the brain, not the number",
   "principle": "Symptoms come from cerebral oedema caused by acute water shift into brain cells. Severity is set by the neurology and the rate of fall, not by how low the number is. A chronic sodium of 118 may be walking and talking. An acute fall to 125 may be fitting.",
   "rule": "Severe neurological symptoms require immediate 3% hypertonic saline—150 mL over 20 minutes in the European guideline—with repeat boluses guided by symptoms and an initial rise of about 5 mmol/L. When safe, obtain serum and urine osmolality and urine sodium before treatment, but do not delay emergency therapy.",
   "trap": "Giving a litre of 0.9% saline to an undifferentiated hyponatraemia. In SIADH this can make the sodium fall further, because the kidney excretes the salt and retains the water.",
   "takehome": "Send the urine before you hang the fluid.",
   "source": "European hyponatraemia clinical practice guideline",
   "check": {
    "label": "European hyponatraemia guideline",
    "url": "https://academic.oup.com/ejendo/article/170/3/G1/6668028"
   }
  },
  {
   "id": 14,
   "system": "renal",
   "theme": "Electrolytes and diabetes",
   "title": "The correction limit that prevents osmotic demyelination",
   "principle": "Brain cells adapt to chronic hyponatraemia by extruding osmolytes. Correct the serum sodium faster than they can reclaim those osmolytes and the cells shrink, causing osmotic demyelination. It is irreversible and it presents days later.",
   "rule": "Limit the rise to no more than 10 mmol/L in the first 24 hours and 8 mmol/L in each 24 hours thereafter; use a more conservative limit, commonly 8 mmol/L per 24 hours, in patients at high risk of osmotic demyelination.",
   "trap": "Auto-correction after the cause is treated—for example after stopping a thiazide or restoring volume—can exceed the limit without further saline. Monitor frequently during active correction and obtain expert help for desmopressin and electrolyte-free water if overcorrection is developing.",
   "takehome": "The danger is not just what you infuse, it is what the patient does once you remove the cause.",
   "source": "European hyponatraemia clinical practice guideline",
   "check": {
    "label": "European hyponatraemia guideline",
    "url": "https://academic.oup.com/ejendo/article/170/3/G1/6668028"
   }
  },
  {
   "id": 15,
   "system": "renal",
   "theme": "Electrolytes and diabetes",
   "title": "In DKA, the long acting insulin stays running",
   "principle": "The fixed rate insulin infusion treats the ketosis. The background basal insulin does a separate job, preventing rebound hyperglycaemia and ketosis at the moment the infusion stops. Stopping it creates a gap.",
   "rule": "Continue the usual long-acting analogue at the usual dose alongside the FRIII. Add 10% glucose when capillary glucose falls below 14 mmol/L and keep insulin running. Resolution is ketones below 0.6 mmol/L with venous pH above 7.3 and/or bicarbonate above 18 mmol/L.",
   "trap": "Stopping the infusion when the glucose normalises. The patient is still ketotic and will relapse within hours.",
   "takehome": "You stop the drip on the ketones, never on the glucose.",
   "source": "JBDS-IP DKA guideline",
   "check": {
    "label": "JBDS adult DKA pathway",
    "url": "https://abcd.care/sites/default/files/site_uploads/JBDS_Guidelines_Current/JBDS_02_Single_page_pathway_March_2023.pdf"
   }
  },
  {
   "id": 16,
   "system": "respiratory",
   "theme": "Respiratory failure",
   "title": "88 to 92% is a target range, not a ceiling to defend",
   "principle": "In oxygen-sensitive hypercapnic respiratory failure, excess oxygen can worsen carbon dioxide retention mainly through ventilation-perfusion mismatch and the Haldane effect; reduced hypoxic drive is a smaller contributor. The target prevents over-oxygenation, not treatment of dangerous hypoxaemia.",
   "rule": "94 to 98% for most acutely unwell patients, 88 to 92% for those at risk of hypercapnic respiratory failure pending blood gases. If a patient at risk is saturating at 80%, give high flow oxygen immediately and check a gas. Do not titrate cautiously upward.",
   "trap": "Leaving a patient hypoxic because they are a retainer. And the opposite, leaving 15 litres running on a non-rebreathe for hours after the patient has stabilised.",
   "takehome": "Correct hypoxia first, then titrate down and check a gas.",
   "source": "BTS oxygen guideline",
   "check": {
    "label": "BTS emergency oxygen guideline",
    "url": "https://www.brit-thoracic.org.uk/clinical-resources/guidelines/emergency-oxygen/"
   }
  },
  {
   "id": 17,
   "system": "respiratory",
   "theme": "Respiratory failure",
   "title": "Start NIV after initial medical therapy—and do not delay it in severe acidosis",
   "principle": "Controlled oxygen and initial COPD treatment can improve reversible acidosis, but persistent hypercapnic acidosis is the evidence-based trigger for NIV and delay can be harmful.",
   "rule": "Give controlled oxygen to 88 to 92% and optimal medical therapy. Start NIV when pH remains below 7.35 with PaCO2 above 6.5 kPa after initial treatment—often reassessed at about 30 to 60 minutes. Severe acidosis, for example pH below 7.25, needs urgent senior review and should not wait for a chest radiograph.",
   "trap": "Treating one hour as an absolute waiting period, or allowing repeated gases to delay ventilation. Document the escalation plan and ceiling of care when NIV starts.",
   "takehome": "Treat first, reassess promptly, and start NIV without delay when hypercapnic acidosis persists.",
   "source": "BTS/ICS acute hypercapnic respiratory failure guideline",
   "check": {
    "label": "BTS/ICS acute NIV guideline",
    "url": "https://thorax.bmj.com/content/71/Suppl_2/ii1"
   }
  },
  {
   "id": 18,
   "system": "respiratory",
   "theme": "Respiratory failure",
   "title": "Five days of prednisolone, and no taper",
   "principle": "For most patients, the recommended five-day oral corticosteroid course can be stopped without a taper. Individualise if the patient has prolonged or repeated steroid exposure or another reason for adrenal suppression.",
   "rule": "Give prednisolone 30 mg once daily for 5 days in an acute COPD exacerbation. Consider antibiotics rather than prescribing them automatically, taking account of sputum colour, volume or thickness, severity, admission risk and evidence of pneumonia.",
   "trap": "The reducing regimen over two weeks, and reflex antibiotics for every exacerbation regardless of sputum character.",
   "takehome": "Thirty milligrams, five days, stop.",
   "source": "NICE NG115 and NG114",
   "check": {
    "label": "NICE COPD recommendations",
    "url": "https://www.nice.org.uk/guidance/ng115/chapter/Recommendations"
   }
  },
  {
   "id": 19,
   "system": "respiratory",
   "theme": "PE, pneumothorax, pneumonia",
   "title": "Age adjusted D-dimer, and when not to send one at all",
   "principle": "D-dimer rises with age, malignancy, infection, pregnancy and surgery. A fixed threshold becomes progressively less useful the older the patient is, generating scans that were never going to be positive.",
   "rule": "In a patient over 50 in whom PE is unlikely, consider an age-adjusted threshold; a commonly validated formula is age multiplied by 10 ng/mL FEU, but confirm the assay units and local pathway. If PE is likely, proceed directly to imaging rather than using D-dimer to rule it out.",
   "trap": "Sending a D-dimer on everyone with chest pain before any clinical assessment. A positive result in a low probability patient then obliges a scan you did not need.",
   "takehome": "Score first, then decide whether the D-dimer means anything.",
   "source": "NICE NG158",
   "check": {
    "label": "NICE NG158 recommendations",
    "url": "https://www.nice.org.uk/guidance/ng158/chapter/Recommendations"
   }
  },
  {
   "id": 20,
   "system": "respiratory",
   "theme": "PE, pneumothorax, pneumonia",
   "title": "Not every PE needs admission",
   "principle": "Early PE risk is driven mainly by haemodynamic status, clinical risk and right-ventricular dysfunction, not simply by the visual size of clot on CT.",
   "rule": "Use a validated tool such as PESI, sPESI or Hestia to identify patients who may be suitable for outpatient treatment, together with clinical judgement, reliable follow-up and safety-netting. Raised troponin or RV dilatation warrants senior risk review and will usually preclude a simple outpatient pathway.",
   "trap": "Calling a PE high risk from clot burden alone. Current risk categories are haemodynamic and clinical; obstruction on the scan must be interpreted with the patient's physiology.",
   "takehome": "The patient's haemodynamics and right heart matter more than how dramatic the clot looks.",
   "source": "NICE NG158 and ESC acute PE guidance",
   "check": {
    "label": "NICE outpatient PE recommendations",
    "url": "https://www.nice.org.uk/guidance/ng158/chapter/Recommendations#outpatient-treatment-for-low-risk-pe"
   }
  },
  {
   "id": 21,
   "system": "respiratory",
   "theme": "PE, pneumothorax, pneumonia",
   "title": "Pneumothorax management moved away from the ruler",
   "principle": "Size on a chest film is a poor guide to how a patient will do. Symptoms and high risk characteristics predict outcome far better than a measurement in centimetres.",
   "rule": "BTS 2023 restructured the pathway around whether the patient is symptomatic and whether high risk characteristics are present, with a much greater role for conservative management and ambulatory devices in stable primary spontaneous pneumothorax. Tension pneumothorax remains a clinical diagnosis needing immediate decompression, never a radiological one.",
   "trap": "Reflexively inserting a chest drain in a minimally symptomatic young patient because the rim measured over 2 cm.",
   "takehome": "Ask how the patient is doing before you measure the film.",
   "source": "BTS pleural disease guideline 2023",
   "check": {
    "label": "BTS pleural disease guideline",
    "url": "https://www.brit-thoracic.org.uk/clinical-resources/guidelines/pleural-disease/"
   }
  },
  {
   "id": 22,
   "system": "infection",
   "theme": "Sepsis and infection",
   "title": "Lactate is a stress marker, not just a perfusion marker",
   "principle": "Lactate rises in shock, but it also rises from beta-2 adrenergic stimulation driving glycolysis, from reduced hepatic clearance, and from any high catecholamine state. The mechanism is not always hypoperfusion.",
   "rule": "Consider the alternatives before assuming sepsis: salbutamol nebulisers, seizures, severe agitation, liver failure, metformin accumulation, thiamine deficiency. A falling lactate after resuscitation is genuinely useful. A single value in isolation is much less so.",
   "trap": "Anchoring on a raised lactate and giving repeated fluid boluses to a patient whose lactate is high for a non-perfusion reason. And the opposite trap, a normal lactate does not exclude sepsis.",
   "takehome": "Trend the lactate, do not treat the single number.",
   "source": "Surviving Sepsis Campaign 2021",
   "check": {
    "label": "Surviving Sepsis Campaign guideline",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8486643/"
   }
  },
  {
   "id": 23,
   "system": "infection",
   "theme": "Sepsis and infection",
   "title": "Neutropenic sepsis: do not wait for the count",
   "principle": "In a neutropenic patient the usual signs of infection are absent because there are no neutrophils to generate them. There may be no localising signs, no pus and minimal inflammatory response, right up until decompensation.",
   "rule": "Suspect neutropenic sepsis in a patient receiving, or recently receiving, anticancer treatment who becomes unwell. Treat it as an acute emergency with immediate empiric broad-spectrum antibiotics; do not wait for the neutrophil count. Follow the local acute-oncology risk window, which is often six weeks, and avoid digital rectal examination.",
   "trap": "Waiting for the neutrophil count, or being reassured because the patient looks reasonably well and is apyrexial. Hypothermia counts too.",
   "takehome": "Antibiotics within the hour, count later.",
   "source": "NICE CG151",
   "check": {
    "label": "NICE neutropenic sepsis recommendations",
    "url": "https://www.nice.org.uk/guidance/cg151/chapter/Recommendations"
   }
  },
  {
   "id": 24,
   "system": "infection",
   "theme": "Sepsis and infection",
   "title": "The blood cultures are worth the two minutes",
   "principle": "Blood cultures can identify the pathogen and support later narrowing of treatment, while antibiotics given first reduce culture yield. Adequate blood volume is a major determinant of sensitivity.",
   "rule": "When bloodstream infection is suspected, collect at least two sets—four bottles—with about 8 to 10 mL in each adult bottle before antibiotics if this causes no clinically important delay. Current UK standards allow both sets to be collected during one venepuncture; follow local policy.",
   "trap": "Skipping cultures because broad-spectrum treatment has started, or delaying time-critical antibiotics while repeatedly attempting difficult cultures. Obtain them promptly, but treatment urgency comes first.",
   "takehome": "Two adequately filled sets before antibiotics when feasible; never create a dangerous treatment delay.",
   "source": "UKHSA blood-culture standards and antimicrobial stewardship guidance",
   "check": {
    "label": "UK antimicrobial stewardship guidance",
    "url": "https://www.gov.uk/government/publications/antimicrobial-stewardship-start-smart-then-focus/start-smart-then-focus-antimicrobial-stewardship-toolkit-for-inpatient-care-settings"
   }
  },
  {
   "id": 25,
   "system": "renal",
   "theme": "Kidneys and fluids",
   "title": "Stopping the ACE inhibitor is not the whole plan",
   "principle": "AKI has three mechanisms and they need different responses. Pre-renal means restore perfusion. Post-renal means relieve obstruction. Intrinsic means find the cause, which is where the drug list and the urine dip actually matter.",
   "rule": "Every AKI gets a volume assessment, a medication review, a urine dip, and consideration of imaging. If there is no obvious cause, arrange renal tract ultrasound within 24 hours. Blood and protein with no infection should prompt thought about glomerulonephritis or vasculitis, which is a same day discussion.",
   "trap": "Stopping the nephrotoxics, prescribing a litre of fluid, and considering the problem addressed. That misses obstruction and misses intrinsic disease.",
   "takehome": "Every AKI needs a urine dip and a reason.",
   "source": "NICE NG148 and KDIGO",
   "check": {
    "label": "NICE acute kidney injury recommendations",
    "url": "https://www.nice.org.uk/guidance/ng148/chapter/Recommendations"
   }
  },
  {
   "id": 26,
   "system": "renal",
   "theme": "Kidneys and fluids",
   "title": "Post-obstructive diuresis is a real thing",
   "principle": "After relief of chronic obstruction the kidney cannot immediately reconcentrate urine. Retained solute plus impaired tubular function produces a large physiological diuresis, which in a minority becomes pathological and causes hypovolaemia and electrolyte collapse.",
   "rule": "After catheterising a patient who drains a large residual volume, monitor hourly urine output and check electrolytes. Replace fluid if output is very high or the patient becomes hypovolaemic, but do not match output millilitre for millilitre by default, because that perpetuates the diuresis.",
   "trap": "Catheterising at 2am, documenting the residual volume, and going back to bed with no monitoring plan written.",
   "takehome": "A big residual volume needs an observation plan, not just a number in the notes.",
   "source": "BAUS teaching and peer-reviewed obstructive uropathy guidance",
   "check": {
    "label": "Review of obstructive uropathy management",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9846865/"
   }
  },
  {
   "id": 27,
   "system": "renal",
   "theme": "Kidneys and fluids",
   "title": "The five Rs, and why maintenance is not resuscitation",
   "principle": "Fluid is a drug with a dose, a route and side effects. The commonest prescribing error is using resuscitation rate fluid to correct a maintenance problem, or the reverse.",
   "rule": "Every fluid prescription answers one of five questions: resuscitation, routine maintenance, replacement of ongoing losses, redistribution, or reassessment. For resuscitation, NICE advises 500 mL of a crystalloid containing sodium 130 to 154 mmol/L over less than 15 minutes, then reassess. Routine maintenance is roughly 25 to 30 mL/kg/day of water with about 1 mmol/kg/day each of sodium, potassium and chloride.",
   "trap": "Continuous 0.9% saline as maintenance. It delivers several times the daily sodium requirement and produces hyperchloraemic acidosis and oedema.",
   "takehome": "Write which of the five Rs you are prescribing for, on the chart.",
   "source": "NICE CG174",
   "check": {
    "label": "NICE IV fluid recommendations",
    "url": "https://www.nice.org.uk/guidance/cg174/chapter/recommendations"
   }
  },
  {
   "id": 28,
   "system": "neurology",
   "theme": "Neurology",
   "title": "The thrombectomy window is far longer than the thrombolysis window",
   "principle": "Whether tissue is salvageable depends on collateral circulation, not on the clock alone. Perfusion imaging identifies patients with a small infarct core and a large threatened penumbra, who benefit long after the standard window.",
   "rule": "Offer thrombolysis within 4.5 hours of known onset when eligible; selected wake-up or unknown-onset strokes may also qualify using advanced imaging. Offer thrombectomy for eligible proximal anterior-circulation occlusion up to 6 hours, and consider it from 6 to 24 hours when imaging shows salvageable tissue.",
   "trap": "Standing down a stroke call because the patient woke with symptoms, or because it is nine hours since onset. That decision belongs to the thrombectomy centre with the imaging in front of them.",
   "takehome": "Late presentation is a reason to call the stroke team, not a reason not to.",
   "source": "NICE NG128",
   "check": {
    "label": "NICE stroke recommendations",
    "url": "https://www.nice.org.uk/guidance/ng128/chapter/Recommendations"
   }
  },
  {
   "id": 29,
   "system": "neurology",
   "theme": "Neurology",
   "title": "Anticoagulants and most antiplatelets change the head-injury CT threshold",
   "principle": "Anticoagulant and antiplatelet treatment can increase the risk of intracranial bleeding after head injury, including when the usual clinical CT indications are absent.",
   "rule": "For a patient on anticoagulants or antiplatelet treatment other than aspirin monotherapy, NICE says to consider CT within 8 hours if there is no other indication, or within 1 hour if they present more than 8 hours after injury. One-hour indications include initial GCS 12 or less, GCS below 15 at 2 hours, skull-fracture signs, seizure, focal deficit or more than one vomiting episode.",
   "trap": "Treating the additional indication as an automatic-scan rule, forgetting it includes antiplatelets except aspirin alone, or discharging without assessing supervision and giving clear delayed-bleeding safety-net advice.",
   "takehome": "Anticoagulants or antiplatelets other than aspirin alone should prompt active consideration of CT even without another indication.",
   "source": "NICE NG232",
   "check": {
    "label": "NICE head injury recommendations",
    "url": "https://www.nice.org.uk/guidance/NG232/chapter/recommendations"
   }
  },
  {
   "id": 30,
   "system": "neurology",
   "theme": "Neurology",
   "title": "4AT takes under two minutes, and confused is not a diagnosis",
   "principle": "Delirium is under-recognised because hypoactive delirium is common, easily missed and can look like fatigue or depression. It is associated with increased mortality and length of stay.",
   "rule": "The 4AT has four components: alertness, orientation with AMT4, attention tested by reciting the months backwards, and evidence of acute change or fluctuation. A score of 4 or above suggests delirium. Then find the cause: infection, retention, constipation, pain, drugs, withdrawal, metabolic derangement.",
   "trap": "Writing confused, for review in the notes. It records the observation without triggering the search for a cause, which is the entire clinical value.",
   "takehome": "Months of the year backwards is a twenty second screening test you can do at the bedside.",
   "source": "NICE CG103 and the 4AT",
   "check": {
    "label": "Official 4AT clinical guide",
    "url": "https://www.the4at.com/aboutthe4at"
   }
  },
  {
   "id": 31,
   "system": "drugs",
   "theme": "Toxicology and GI bleeding",
   "title": "The two bag paracetamol regimen",
   "principle": "Non-IgE-mediated reactions to acetylcysteine are related in part to the high initial infusion rate in the traditional regimen. In studies, the slower two-bag SNAP regimen reduced adverse reactions without increasing liver injury.",
   "rule": "The SNAP regimen gives 100 mg/kg over 2 hours then 200 mg/kg over 10 hours. It is off-label and not universal, so use TOXBASE and the adopted local protocol. If a reaction occurs, manage it according to that protocol and obtain toxicology advice rather than labelling acetylcysteine as a permanent allergy.",
   "trap": "Stopping acetylcysteine permanently after a flushing reaction and leaving the patient untreated.",
   "takehome": "An acetylcysteine reaction means slow the infusion, not stop the treatment.",
   "source": "SNAP clinical studies. This regimen is off-label; follow TOXBASE and local policy",
   "check": {
    "label": "SNAP regimen safety and efficacy study",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC6610779/"
   }
  },
  {
   "id": 32,
   "system": "drugs",
   "theme": "Toxicology and GI bleeding",
   "title": "Give thiamine with glucose—but never delay emergency glucose",
   "principle": "Thiamine is required for carbohydrate metabolism. Prolonged carbohydrate administration to a severely thiamine-deficient patient may worsen or precipitate Wernicke's encephalopathy, but evidence does not support withholding urgent glucose.",
   "rule": "Treat hypoglycaemia immediately. In patients at risk through alcohol dependence, malnutrition or prolonged vomiting, give parenteral thiamine before, alongside or promptly after glucose without delaying glucose delivery. Do not wait for the classic triad of confusion, ataxia and eye signs.",
   "trap": "Delaying glucose in a hypoglycaemic patient while sourcing thiamine, or waiting for the full Wernicke triad before treating thiamine deficiency.",
   "takehome": "Emergency glucose comes first; give thiamine promptly as well when deficiency is plausible.",
   "source": "NICE CG100 and evidence review of glucose-before-thiamine",
   "check": {
    "label": "Glucose-before-thiamine evidence review",
    "url": "https://www.sciencedirect.com/science/article/pii/S0736467911008547"
   }
  },
  {
   "id": 33,
   "system": "gastro",
   "theme": "Toxicology and GI bleeding",
   "title": "A Blatchford score of 0 or 1 may support outpatient care",
   "principle": "The Glasgow-Blatchford score is built entirely from pre-endoscopy variables and predicts need for intervention. It is the only widely used bleeding score designed for exactly the decision you are making at 3am.",
   "rule": "Calculate Glasgow-Blatchford score at presentation. BSG guidance supports considering outpatient management at a score of 0 or 1 if the wider clinical and social assessment is safe; NICE specifically highlights a score of 0 for early discharge. Patients admitted should undergo endoscopy within 24 hours, or urgently after resuscitation if unstable.",
   "trap": "Using the score as an automatic discharge instruction, or transfusing a stable patient to a normal haemoglobin. A restrictive threshold around 70 g/L is usual for most stable patients, but haemodynamic instability and acute coronary disease require individualisation.",
   "takehome": "Blatchford before endoscopy, Rockall after.",
   "source": "BSG acute upper GI bleeding care bundle and NICE CG141",
   "check": {
    "label": "BSG acute upper GI bleeding care bundle",
    "url": "https://www.bsg.org.uk/clinical-resource/bsge-acute-upper-gi-bleed-care-bundle"
   }
  },
  {
   "id": 34,
   "system": "drugs",
   "theme": "Peri-arrest and prescribing",
   "title": "Anaphylaxis: the drug is adrenaline and the site is the thigh",
   "principle": "The anterolateral thigh has large muscle bulk and high blood flow, giving the fastest reliable peak concentration. Adrenaline is the only drug that reverses the underlying pathology rather than one symptom of it.",
   "rule": "Give 500 micrograms of 1 mg/mL adrenaline IM into the anterolateral thigh in an adult and repeat after 5 minutes if there is no improvement. Lie the patient flat with legs raised; a patient with severe breathing difficulty may sit with legs extended, but do not let them stand or walk.",
   "trap": "Reaching for chlorphenamine and hydrocortisone first. Both were removed from the RCUK 2021 acute algorithm because neither does anything for airway compromise or shock.",
   "takehome": "After two IM doses without response, call for expert help and start an IV adrenaline infusion; continue 5-minute IM doses until the infusion is running.",
   "source": "Resuscitation Council UK guideline 2025 and refractory anaphylaxis guidance",
   "check": {
    "label": "RCUK special-circumstances guideline",
    "url": "https://www.resus.org.uk/professional-library/2025-resuscitation-guidelines/special-circumstances-guidelines"
   }
  },
  {
   "id": 35,
   "system": "drugs",
   "theme": "Peri-arrest and prescribing",
   "title": "A common preventable cause of long QT is on the drug chart",
   "principle": "The QT interval reflects ventricular repolarisation, mostly via potassium channels. Many common drugs block those channels and the effect is additive when you stack them. Hypokalaemia, hypomagnesaemia and bradycardia all amplify it.",
   "rule": "QTc above 500 ms, or an increase of more than 60 ms from baseline, is high risk. Review QT-prolonging medicines and interactions, correct hypokalaemia and hypomagnesaemia into the normal or high-normal range as locally advised, and obtain senior advice if risk persists.",
   "trap": "Prescribing ondansetron and clarithromycin together to a hypokalaemic patient already on citalopram, and never looking at an ECG. This is one of the more preventable causes of in-hospital torsades.",
   "takehome": "Before adding a QT prolonging drug, look at the potassium and at what is already on the chart.",
   "source": "MHRA drug safety updates and peer-reviewed QT guidance",
   "check": {
    "label": "Review of drug-induced QT prolongation",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4860751/"
   }
  },
  {
   "id": 36,
   "system": "drugs",
   "theme": "Peri-arrest and prescribing",
   "title": "Digoxin toxicity happens at normal levels",
   "principle": "Serum digoxin concentration does not reliably correlate with toxicity, especially in chronic exposure. Renal impairment, hypokalaemia and hypomagnesaemia increase susceptibility, so toxicity can occur within the quoted therapeutic range.",
   "rule": "Diagnose from the clinical picture, ECG, renal function, electrolytes and a correctly timed level—at least 6 hours after the last dose. Digoxin-specific antibody fragments are indicated for life-threatening toxicity; discuss significant suspected toxicity with toxicology early.",
   "trap": "Excluding toxicity because the level came back in range, and taking the level too soon after a dose, when it is uninterpretable before six hours.",
   "takehome": "Low potassium makes a normal digoxin level dangerous.",
   "source": "TOXBASE and expert consensus guidance",
   "check": {
    "label": "Digoxin-toxicity consensus guidance",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10599802/"
   }
  },
  {
   "id": 37,
   "system": "gastro",
   "theme": "Gastroenterology and hepatology",
   "title": "Every admission with ascites gets a diagnostic tap",
   "principle": "In cirrhosis the ascitic fluid is a culture medium and the gut wall is leaky, so infection arises with no perforation and no surgical source. It frequently presents without abdominal pain or fever, sometimes as nothing more than a rising creatinine or new confusion.",
   "rule": "Perform diagnostic paracentesis without delay in every hospital admission with cirrhotic ascites, ideally before antibiotics. An ascitic neutrophil count above 250 cells/mm³ establishes spontaneous bacterial peritonitis. Treat with antibiotics; BSG/BASL recommends albumin when creatinine is increased or rising.",
   "trap": "Not tapping because the patient looks well or because coagulation tests are abnormal. Routine prothrombin-time or platelet measurement and prophylactic blood products are not recommended before paracentesis.",
   "takehome": "Two hundred and fifty neutrophils is the number, and the culture does not have to be positive.",
   "source": "BSG/BASL ascites guideline",
   "check": {
    "label": "BSG/BASL ascites guideline",
    "url": "https://gut.bmj.com/content/70/1/9"
   }
  },
  {
   "id": 38,
   "system": "gastro",
   "theme": "Gastroenterology and hepatology",
   "title": "Encephalopathy is a search for the precipitant",
   "principle": "Overt hepatic encephalopathy commonly has an identifiable precipitant. Treating infection, bleeding, constipation, dehydration, electrolyte disturbance or sedating medicines is central to recovery.",
   "rule": "Look for it every time: infection including SBP, gastrointestinal bleeding, constipation, dehydration or over-diuresis, electrolyte disturbance, and sedative drugs. Lactulose titrated to two or three soft stools a day, with rifaximin added for recurrent episodes.",
   "trap": "Using an elevated ammonia level to diagnose or grade encephalopathy. It correlates poorly with severity; a normal value should prompt diagnostic reconsideration. Also exclude other causes of confusion such as hypoglycaemia, sepsis, Wernicke's encephalopathy or subdural bleeding.",
   "takehome": "Hepatic encephalopathy is a clinical diagnosis; search for and treat the precipitant.",
   "source": "EASL/AASLD hepatic encephalopathy guidance",
   "check": {
    "label": "AASLD hepatic encephalopathy review",
    "url": "https://www.aasld.org/liver-fellow-network/core-series/back-basics/back-basics-decoding-hepatic-encephalopathy"
   }
  },
  {
   "id": 39,
   "system": "gastro",
   "theme": "Gastroenterology and hepatology",
   "title": "In cirrhotic bleeding, antibiotics are a mortality treatment",
   "principle": "Bacterial infection is common around acute variceal bleeding and increases rebleeding and death. Antibiotic prophylaxis improves survival; vasoactive treatment and timely endoscopic haemostasis are also core mortality-focused care.",
   "rule": "Start antibiotic prophylaxis from admission for cirrhosis with upper gastrointestinal bleeding. If variceal bleeding is suspected, start terlipressin unless contraindicated and arrange endoscopy within 12 hours once haemodynamically resuscitated.",
   "trap": "Waiting for endoscopy to confirm varices before starting either drug. And over-transfusing, which raises portal pressure and provokes rebleeding, so hold to the restrictive threshold of 70 g/L.",
   "takehome": "Antibiotics in a cirrhotic bleed are a mortality intervention, not optional prophylaxis.",
   "source": "NICE CG141, BSG and Baveno VII guidance",
   "check": {
    "label": "Baveno VII consensus",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC11090185/"
   }
  },
  {
   "id": 40,
   "system": "gastro",
   "theme": "Gastroenterology and hepatology",
   "title": "Pancreatic enzymes help diagnose pancreatitis, not grade its severity",
   "principle": "Early mortality in acute pancreatitis is driven by SIRS and organ failure, not by the pancreas itself. The enzyme level reflects neither how much gland is involved nor how sick the patient will become.",
   "rule": "Diagnosis requires two of three: characteristic pain, amylase or preferably lipase more than three times the upper limit of normal, or characteristic imaging. Use moderate, goal-directed fluid resuscitation—lactated Ringer's is preferred—find the cause with ultrasound and history, and check calcium and triglycerides when appropriate.",
   "trap": "Prophylactic antibiotics with no proven infection, which do not improve outcome. And keeping patients nil by mouth by reflex, when early oral feeding as tolerated is now preferred in mild disease.",
   "takehome": "A normal or mildly raised amylase does not reassure, and a very high one does not frighten.",
   "source": "ACG 2024 and international acute pancreatitis guidance",
   "check": {
    "label": "ACG acute pancreatitis guideline",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC13221274/"
   }
  },
  {
   "id": 41,
   "system": "gastro",
   "theme": "Gastroenterology and hepatology",
   "title": "Acute severe colitis: day three is the decision point",
   "principle": "Acute severe ulcerative colitis carries real mortality and its decision points are time bound. Truelove and Witts criteria identify it on day one, and failure to respond by day three is what triggers rescue therapy or surgery.",
   "rule": "Six or more bloody stools a day plus any one of: temperature above 37.8°C, pulse above 90, haemoglobin below 105 g/L, or ESR above 30 mm/hour. Admit for intravenous steroids, stool chart, C. difficile testing, early flexible sigmoidoscopy with biopsies including for CMV, and appropriate abdominal imaging. Assess response on day 3 with the IBD and surgical teams involved early.",
   "trap": "Withholding pharmacological VTE prophylaxis solely because of rectal bleeding. Acute severe colitis is strongly prothrombotic and prophylaxis is indicated unless there is a true contraindication. Avoid antimotility drugs and opioids because of toxic-megacolon risk.",
   "takehome": "Rectal bleeding is not a reason to withhold VTE prophylaxis in colitis.",
   "source": "BSG inflammatory bowel disease guideline 2025",
   "check": {
    "label": "BSG adult IBD guideline 2025",
    "url": "https://www.bsg.org.uk/clinical-resource/bsg-guidelines-on-ibd-in-adults-2025"
   }
  }
 ],
 "order": [
  1,
  2,
  3,
  4,
  5,
  6,
  9,
  16,
  17,
  18,
  19,
  20,
  21,
  10,
  11,
  12,
  13,
  14,
  15,
  25,
  26,
  27,
  33,
  37,
  38,
  39,
  40,
  41,
  7,
  8,
  28,
  29,
  30,
  22,
  23,
  24,
  31,
  32,
  34,
  35,
  36
 ]
};
