#!/usr/bin/env node
/*
 * Builds the site from data/*.csv + src/*.
 *
 *   node scripts/build.mjs            -> writes the site files into the repo root
 *   node scripts/build.mjs --out dist -> assembles a clean folder for deployment
 *
 * Everything the page needs comes out of the two CSVs, so adding a teaching
 * point means adding a row — no code change.
 */
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, rmSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

/* Static files that ship with the site but are not generated. */
const ASSETS = [
  "CNAME",
  "site.webmanifest",
  "favicon.ico",
  "favicon.svg",
  "favicon-16.png",
  "favicon-32.png",
  "apple-touch-icon.png",
  "icon-192.png",
  "icon-512.png",
  "icon-maskable-512.png",
  "og-image.png",
];

/* ---------- CSV ---------- */

/* RFC 4180: quoted fields may contain commas, newlines and doubled quotes. */
function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = "";
  let quoted = false;
  const src = text.replace(/^﻿/, "").replace(/\r\n?/g, "\n");

  for (let i = 0; i < src.length; i++) {
    const ch = src[i];
    if (quoted) {
      if (ch === '"') {
        if (src[i + 1] === '"') { field += '"'; i++; }
        else quoted = false;
      } else field += ch;
      continue;
    }
    if (ch === '"') quoted = true;
    else if (ch === ",") { row.push(field); field = ""; }
    else if (ch === "\n") { row.push(field); rows.push(row); row = []; field = ""; }
    else field += ch;
  }
  if (field !== "" || row.length) { row.push(field); rows.push(row); }

  const header = rows.shift().map((h) => h.trim());
  return rows
    .filter((r) => r.some((v) => v.trim() !== ""))
    .map((r, n) => {
      if (r.length !== header.length) {
        throw new Error(`row ${n + 2} has ${r.length} fields, expected ${header.length}`);
      }
      return Object.fromEntries(header.map((h, i) => [h, r[i].trim()]));
    });
}

function readCsv(name) {
  return parseCsv(readFileSync(join(ROOT, "data", name), "utf8"));
}

/* ---------- load and validate ---------- */

function loadData() {
  const systems = readCsv("systems.csv").map((s, i) => ({
    key: s.key,
    name: s.name,
    colour: s.colour,
    order: i,
  }));

  const byKey = new Map(systems.map((s) => [s.key, s]));
  const problems = [];

  systems.forEach((s) => {
    if (!/^#[0-9A-Fa-f]{6}$/.test(s.colour)) {
      problems.push(`system "${s.key}": colour "${s.colour}" is not a #RRGGBB hex value`);
    }
  });

  const required = ["id", "system", "theme", "title", "principle", "rule", "trap", "takehome", "source", "check_label", "check_url"];
  const seen = new Set();

  const topics = readCsv("topics.csv").map((t, i) => {
    const where = `topic row ${i + 2}`;
    required.forEach((f) => {
      if (!t[f]) problems.push(`${where}: "${f}" is empty`);
    });
    const id = Number(t.id);
    if (!Number.isInteger(id) || id < 1) problems.push(`${where}: id "${t.id}" is not a positive whole number`);
    if (seen.has(id)) problems.push(`${where}: id ${id} is used more than once`);
    seen.add(id);
    if (!byKey.has(t.system)) {
      problems.push(`${where}: system "${t.system}" is not in systems.csv`);
    }
    if (t.check_url && !/^https?:\/\//.test(t.check_url)) {
      problems.push(`${where}: check_url "${t.check_url}" must start with http:// or https://`);
    }
    return {
      id,
      system: t.system,
      theme: t.theme,
      title: t.title,
      principle: t.principle,
      rule: t.rule,
      trap: t.trap,
      takehome: t.takehome,
      source: t.source,
      check: { label: t.check_label, url: t.check_url },
    };
  });

  if (!topics.length) problems.push("topics.csv has no rows");
  if (problems.length) {
    throw new Error("data problems:\n  - " + problems.join("\n  - "));
  }

  /* Wheel order: grouped by system in systems.csv order, id order within. */
  const order = [];
  systems.forEach((s) => {
    topics.filter((t) => t.system === s.key)
      .sort((a, b) => a.id - b.id)
      .forEach((t) => order.push(t.id));
  });

  return { systems, topics, order };
}

/* ---------- outputs ---------- */

function writeDataScript(outDir, data) {
  const body =
    "/* Generated by scripts/build.mjs from data/*.csv. Do not edit by hand. */\n" +
    "window.WHEEL_DATA = " + JSON.stringify(data, null, 1) + ";\n";
  writeFileSync(join(outDir, "data.js"), body, "utf8");
}

/* Pages serves these with max-age=600, so without a version in the URL a
   returning visitor can get new HTML alongside a ten-minute-old app.js or
   data.js. Stamping the content hash makes each deploy land in one piece. */
function writeIndex(outDir) {
  const stamp = (file) => {
    const hash = createHash("sha1").update(readFileSync(join(outDir, file))).digest("hex").slice(0, 8);
    return `${file}?v=${hash}`;
  };
  let html = readFileSync(join(ROOT, "src", "index.html"), "utf8");
  [
    ['href="styles.css"', `href="${stamp("styles.css")}"`],
    ['src="data.js"', `src="${stamp("data.js")}"`],
    ['src="app.js"', `src="${stamp("app.js")}"`],
  ].forEach(([from, to]) => {
    if (!html.includes(from)) throw new Error(`src/index.html no longer contains ${from}`);
    html = html.replace(from, to);
  });
  writeFileSync(join(outDir, "index.html"), html, "utf8");
}

function writeRota(outDir, { systems, topics }) {
  const header = readFileSync(join(ROOT, "src", "rota-header.md"), "utf8").trimEnd();
  const footer = readFileSync(join(ROOT, "src", "rota-footer.md"), "utf8").trimEnd();

  const table = [
    "## The set",
    "",
    "| System | Topics | Numbers |",
    "|---|---|---|",
    ...systems.map((s) => {
      const ids = topics.filter((t) => t.system === s.key).map((t) => t.id);
      return `| ${s.name} | ${ids.length} | ${ids.join(", ")} |`;
    }),
    `| **Total** | **${topics.length}** | |`,
  ].join("\n");

  const sections = systems.map((s) => {
    const mine = topics.filter((t) => t.system === s.key).sort((a, b) => a.id - b.id);
    if (!mine.length) return "";
    return [
      `# ${s.name}`,
      "",
      mine.map((t) => [
        `## ${t.id}. ${t.title}`,
        "",
        `**Principle:** ${t.principle}`,
        "",
        `**Rule:** ${t.rule}`,
        "",
        `**Trap:** ${t.trap}`,
        "",
        `**Take home:** ${t.takehome}`,
        "",
        `**Source:** ${t.source}`,
        "",
        `**Fact check:** [${t.check.label}](${t.check.url})`,
      ].join("\n")).join("\n\n---\n\n"),
    ].join("\n");
  }).filter(Boolean);

  const doc = [header, "", table, "", "---", "", sections.join("\n\n---\n\n"), "", "---", "", footer, ""].join("\n");
  writeFileSync(join(outDir, "handover-teaching-rota.md"), doc, "utf8");
}

/* ---------- run ---------- */

const argOut = process.argv.indexOf("--out");
const outDir = argOut > -1 ? resolve(ROOT, process.argv[argOut + 1]) : ROOT;
const isRoot = outDir === ROOT;

if (!isRoot) {
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });
}

const data = loadData();

["styles.css", "app.js"].forEach((f) => {
  copyFileSync(join(ROOT, "src", f), join(outDir, f));
});
writeDataScript(outDir, data);
writeRota(outDir, data);
writeIndex(outDir);

if (!isRoot) {
  ASSETS.forEach((f) => copyFileSync(join(ROOT, f), join(outDir, f)));
}

const counts = data.systems
  .map((s) => `${s.name} ${data.topics.filter((t) => t.system === s.key).length}`)
  .join(", ");
console.log(`Built ${data.topics.length} topics into ${isRoot ? "the repo root" : outDir}`);
console.log(`  ${counts}`);
